require 'Items/SuburbsDistributions'

table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.2);
table.insert(SuburbsDistributions["fossoil"]["counter"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["fossoil"]["counter"].items, 0.1);
table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.2);
table.insert(SuburbsDistributions["all"]["postbox"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["all"]["postbox"].items, 0.2);
table.insert(SuburbsDistributions["all"]["sidetable"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["all"]["sidetable"].items, 0.7);
table.insert(SuburbsDistributions["all"]["shelves"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["all"]["shelves"].items, 1);
table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["shed"]["other"].items, 0.5);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 0.5);
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, 0.5);
table.insert(SuburbsDistributions["bookstore"]["other"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["bookstore"]["other"].items, 1);
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, 0.2);
table.insert(SuburbsDistributions["toolstore"]["counter"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["toolstore"]["counter"].items, 0.2);
table.insert(SuburbsDistributions["mechanic"]["wardrobe"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["mechanic"]["wardrobe"].items, 1);
table.insert(SuburbsDistributions["mechanic"]["metal_shelves"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["mechanic"]["metal_shelves"].items, 0.3);
table.insert(SuburbsDistributions["poststorage"]["all"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["poststorage"]["all"].items, 0.5);
table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "Aquatsar.BoatMag");
table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.2);


table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.2);
table.insert(SuburbsDistributions["fossoil"]["counter"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["fossoil"]["counter"].items, 0.1);
table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.2);
table.insert(SuburbsDistributions["all"]["postbox"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["all"]["postbox"].items, 0.2);
table.insert(SuburbsDistributions["all"]["sidetable"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["all"]["sidetable"].items, 0.7);
table.insert(SuburbsDistributions["all"]["shelves"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["all"]["shelves"].items, 1);
table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["shed"]["other"].items, 0.5);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 0.5);
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, 0.5);
table.insert(SuburbsDistributions["bookstore"]["other"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["bookstore"]["other"].items, 1);
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, 0.2);
table.insert(SuburbsDistributions["toolstore"]["counter"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["toolstore"]["counter"].items, 0.2);
table.insert(SuburbsDistributions["mechanic"]["wardrobe"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["mechanic"]["wardrobe"].items, 1);
table.insert(SuburbsDistributions["mechanic"]["metal_shelves"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["mechanic"]["metal_shelves"].items, 0.3);
table.insert(SuburbsDistributions["poststorage"]["all"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["poststorage"]["all"].items, 0.5);
table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "Aquatsar.SwimMag");
table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.2);


table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.BoatPropeller");
table.insert(SuburbsDistributions["shed"]["other"].items, 1);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.BoatPropeller");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 1);

table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.ManualStarter");
table.insert(SuburbsDistributions["shed"]["other"].items, 1);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.ManualStarter");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 1);

table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.Sails");
table.insert(SuburbsDistributions["shed"]["other"].items, 1);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.Sails");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 1);

--------------------------------------

table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["shed"]["other"].items, 2);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 2);
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, 2);
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, 7);
table.insert(SuburbsDistributions["toolstore"]["counter"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["toolstore"]["counter"].items, 6);
table.insert(SuburbsDistributions["fishingstorage"]["crate"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["fishingstorage"]["crate"].items, 5);
table.insert(SuburbsDistributions["camping"]["counter"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["camping"]["counter"].items, 4);
table.insert(SuburbsDistributions["camping"]["shelves"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["camping"]["shelves"].items, 4);
table.insert(SuburbsDistributions["campingstorage"]["crate"].items, "Aquatsar.Compass");
table.insert(SuburbsDistributions["campingstorage"]["crate"].items, 4);

table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["shed"]["other"].items, 2);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 2);
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, 2);
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, 7);
table.insert(SuburbsDistributions["toolstore"]["counter"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["toolstore"]["counter"].items, 6);
table.insert(SuburbsDistributions["fishingstorage"]["crate"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["fishingstorage"]["crate"].items, 5);
table.insert(SuburbsDistributions["camping"]["counter"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["camping"]["counter"].items, 4);
table.insert(SuburbsDistributions["camping"]["shelves"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["camping"]["shelves"].items, 4);
table.insert(SuburbsDistributions["campingstorage"]["crate"].items, "Aquatsar.DivingMask");
table.insert(SuburbsDistributions["campingstorage"]["crate"].items, 4);

table.insert(SuburbsDistributions["shed"]["other"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["shed"]["other"].items, 2);
table.insert(SuburbsDistributions["garagestorage"]["other"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["garagestorage"]["other"].items, 2);
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["garage"]["metal_shelves"].items, 2);
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, 7);
table.insert(SuburbsDistributions["toolstore"]["counter"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["toolstore"]["counter"].items, 6);
table.insert(SuburbsDistributions["fishingstorage"]["crate"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["fishingstorage"]["crate"].items, 5);
table.insert(SuburbsDistributions["camping"]["counter"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["camping"]["counter"].items, 4);
table.insert(SuburbsDistributions["camping"]["shelves"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["camping"]["shelves"].items, 4);
table.insert(SuburbsDistributions["campingstorage"]["crate"].items, "Aquatsar.Lifebuoy");
table.insert(SuburbsDistributions["campingstorage"]["crate"].items, 4);

